version: '2.2'
services:
  dmhy_notifier_docker:
    build:
      context: ./
      dockerfile: Dockerfile
#    image: ghcr.io/kin021360/dmhy-notifier:latest
#    pull_policy: always
#    volumes:
#      - /:/home/dmhy-notifier/leveldb
    environment:
      - NODE_ENV=production
      - tgBotToken=
      - magnetHelperLink=
      - esLogEndpoint=
      - esLogIndex=
    restart: always
