version: '2.2'
services:
  dmhy_notifier_docker:
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #     - /:/home/dmhy-notifier/leveldb
    environment:
      - NODE_ENV=production
      - tgBotToken=''
      - magnetHelperLink=''
    restart: always
