name: Build and push Docker image to ghcr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  workflow_run:
#    workflows: ["Stage"]
#    types:
#      - completed

jobs:
  docker_push:
    name: Docker image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Step
        run: echo ${GITHUB_SHA::7}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/kin021360/dmhy-notifier:latest
