# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push
#    branches: [ * ]
#  pull_request:
#    branches: [ master ]

jobs:
#  build:
#    name: 'Test & Lint'
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [14.x]
#    steps:
#    - name: Checkout source
#      uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: yarn install
#    - run: yarn lint
#    - run: yarn build
  docker_push:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Step
        run: echo ${GITHUB_SHA::7}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          registry: ghcr.io
          username: "kin021360"
          password: ${{ secrets.PAT }}
          repository: kin021360/dmhy-notifier
          tags: latest
